site_name: Abhinav Vadlapatla

theme:
  name: material
  palette:
    primary: blue
  #custom_dir: overrides
  features:
    - instant
    - tabs

nav:
  - 'Home' : index.md
  - EKS:
    - 'Setup EKS Cluster' : eks/cluster.md
    - 'Cluster Autoscaler on Fargate': eks/fargate_autoscaler.md
    - 'Customizing kubelet': eks/kubelet_customization.md

markdown_extensions:
  - toc:
      permalink: true
  - attr_list

repo_url: https://github.com/avadlapatla/blog/

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/abhinav-vadlapatla/

copyright: "Copyright &copy; 2020 Abhinav Vadlapatla"