site_name: Abhinav's Blog

# theme:
#   name: material
#   palette:
#     primary: blue
#   #custom_dir: overrides
#   features:
#     - instant
#     - tabs

theme:
  name: 'material'
  custom_dir: 'theme'
  language: en
  include_sidebar: true
  favicon: assets/img/favicon.png
  logo: assets/img/clouds.png
  palette:
    primary: 'cyan'
    accent: 'cyan'

nav:
  - 'Welcome' : index.md
  - EKS:
    - 'Setup EKS Cluster' : eks/cluster.md
    - 'Cluster Autoscaler on Fargate': eks/fargate_autoscaler.md
    - 'Customizing kubelet': eks/kubelet_customization.md

markdown_extensions:
  - toc:
      permalink: true
  - attr_list

repo_url: https://github.com/avadlapatla/blog/

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/abhinav-vadlapatla/

copyright: "Copyright &copy; 2020 Abhinav Vadlapatla"